-- |
-- Module      : LLMLL.Codegen
-- Description : Transpile LLMLL AST to Rust source code.
--
-- Converts the LLMLL AST into idiomatic Rust code that:
--   * Defines each `def-logic` as a Rust `fn` with typed parameters
--   * Emits pre/post contracts as `assert!` macros (debug build) or runtime panics
--   * Converts `check` blocks into `#[test]` functions using `proptest`
--   * Maps LLMLL types to Rust types (i64, f64, String, bool, Vec<T>, etc.)
--   * Emits a `Cargo.toml` for the generated crate
--
-- In v0.1, expressions are translated directly.
-- Complex features (dependent types, async delegates, WASM) are stubs
-- marked with TODO comments in generated code.
module LLMLL.Codegen
  ( -- * Entry Points
    generateRust
  , generateCargoToml
  , CodegenResult(..)
  , CodegenError(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Data.List (intercalate)

import LLMLL.Syntax

-- ---------------------------------------------------------------------------
-- Result Types
-- ---------------------------------------------------------------------------

data CodegenError
  = UnsupportedFeature Text
  | UnresolvedHole Text
  | CodegenInternalError Text
  deriving (Show, Eq)

data CodegenResult = CodegenResult
  { cgRustSource  :: Text         -- ^ Generated Rust source for lib.rs
  , cgCargoToml   :: Text         -- ^ Generated Cargo.toml
  , cgModuleName  :: Text         -- ^ The module name used
  , cgWarnings    :: [Text]       -- ^ Non-fatal issues encountered
  } deriving (Show, Eq)

-- ---------------------------------------------------------------------------
-- Code Generation State
-- ---------------------------------------------------------------------------

data CgEnv = CgEnv
  { cgIndent   :: Int      -- ^ Current indentation level
  , cgWarnings' :: [Text]  -- ^ Accumulated warnings
  } deriving (Show)

defaultEnv :: CgEnv
defaultEnv = CgEnv 0 []

-- ---------------------------------------------------------------------------
-- Entry Points
-- ---------------------------------------------------------------------------

-- | Generate Rust source from a list of top-level statements.
generateRust :: Text -> [Statement] -> CodegenResult
generateRust moduleName stmts =
  let (warnings, source) = runCodegen moduleName stmts
  in CodegenResult
    { cgRustSource  = source
    , cgCargoToml   = generateCargoToml moduleName
    , cgModuleName  = moduleName
    , cgWarnings    = warnings
    }

-- | Generate Cargo.toml for the emitted Rust crate.
generateCargoToml :: Text -> Text
generateCargoToml moduleName = T.unlines
  [ "[package]"
  , "name = \"" <> T.replace "_" "-" moduleName <> "\""
  , "version = \"0.1.0\""
  , "edition = \"2021\""
  , ""
  , "[dependencies]"
  , "# LLMLL runtime support"
  , ""
  , "[dev-dependencies]"
  , "proptest = \"1\""
  , ""
  , "[lib]"
  , "name = \"" <> moduleName <> "\""
  , "path = \"src/lib.rs\""
  ]

-- ---------------------------------------------------------------------------
-- Main Code Generator
-- ---------------------------------------------------------------------------

runCodegen :: Text -> [Statement] -> ([Text], Text)
runCodegen moduleName stmts =
  let warnings  = concatMap (stmtWarnings moduleName) stmts
      imports   = T.unlines
        [ "// Generated by LLMLL compiler v0.1"
        , "// DO NOT EDIT — regenerate with `llmll build`"
        , "#![allow(unused_variables, dead_code)]"
        , ""
        , "use std::collections::HashMap;"
        , ""
        ]
      -- Type definitions first
      typeDefs  = T.unlines (map emitStatement (filter isTypeDef stmts))
      -- Interface traits
      ifaces    = T.unlines (map emitStatement (filter isInterface stmts))
      -- Functions
      fns       = T.unlines (map emitStatement (filter isFn stmts))
      -- Tests module
      tests     = emitTestModule moduleName (filter isCheck stmts)
      source    = imports <> typeDefs <> ifaces <> fns <> tests
  in (warnings, source)

isTypeDef, isInterface, isFn, isCheck :: Statement -> Bool
isTypeDef  (STypeDef{})   = True
isTypeDef  _              = False
isInterface (SDefInterface{}) = True
isInterface _             = False
isFn       (SDefLogic{})  = True
isFn       _              = False
isCheck    (SCheck{})     = True
isCheck    _              = False

-- ---------------------------------------------------------------------------
-- Statement Emitters
-- ---------------------------------------------------------------------------

emitStatement :: Statement -> Text
emitStatement (STypeDef name body) = emitTypeDef name body
emitStatement (SDefInterface name fns) = emitInterface name fns
emitStatement (SDefLogic name params mRet contract body) =
  emitFunction name params mRet contract body
emitStatement (SCheck prop) = ""  -- handled in emitTestModule
emitStatement _ = ""

-- | Emit a Rust type alias or struct.
emitTypeDef :: Name -> Type -> Text
emitTypeDef name body = case body of
  TCustom desc ->
    "// type " <> name <> " = " <> desc <> "\n"
    <> "pub type " <> toRustIdent name <> " = " <> emitType body <> ";\n\n"
  TDependent base constraint ->
    "/// Dependent type: `" <> name <> "` — constraint checked at runtime\n"
    <> "/// Constraint: " <> emitExprInline constraint <> "\n"
    <> "pub type " <> toRustIdent name <> " = " <> emitType base <> ";\n"
    <> "\n"
    <> "pub fn validate_" <> toRustIdent name <> "(x: &" <> emitType base <> ") -> bool {\n"
    <> "    " <> emitExprInline constraint <> " // TODO: substitute x into constraint\n"
    <> "}\n\n"
  _ ->
    "pub type " <> toRustIdent name <> " = " <> emitType body <> ";\n\n"

-- | Emit a Rust trait for a def-interface.
emitInterface :: Name -> [(Name, Type)] -> Text
emitInterface name fns = T.unlines $
  [ "pub trait " <> toRustIdent name <> " {" ]
  ++ map emitTraitMethod fns
  ++ [ "}" , "" ]

emitTraitMethod :: (Name, Type) -> Text
emitTraitMethod (fname, TFn argTypes retType) =
  "    fn " <> toRustIdent fname
  <> "(&self, " <> emitArgs argTypes <> ") -> " <> emitType retType <> ";"
  where
    emitArgs tys = T.intercalate ", "
      [ "arg" <> T.pack (show i) <> ": " <> emitType t
      | (i, t) <- zip [(0::Int)..] tys
      ]
emitTraitMethod (fname, other) =
  "    // " <> fname <> ": " <> typeLabel other <> " (non-fn type)"

-- | Emit a Rust function from def-logic.
emitFunction :: Name -> [(Name, Type)] -> Maybe Type -> Contract -> Expr -> Text
emitFunction name params mRet contract body = T.unlines
  [ docComment
  , "pub fn " <> toRustIdent name
    <> "(" <> emitParams params <> ") -> " <> retTypeStr <> " {"
  , preCheck
  , "    let result = " <> emitExprIndented body 1 <> ";"
  , postCheck
  , "    result"
  , "}"
  , ""
  ]
  where
    retTypeStr = maybe "()" emitType mRet
    docComment = "/// LLMLL def-logic: `" <> name <> "`"
    preCheck   = case contractPre contract of
      Nothing   -> ""
      Just expr -> "    assert!(" <> emitExprInline expr
                   <> ", \"Precondition violated in " <> name <> "\");"
    postCheck  = case contractPost contract of
      Nothing   -> ""
      Just expr -> "    let _post_check = " <> emitExprInline (substResult expr) <> ";\n"
                   <> "    assert!(_post_check, \"Postcondition violated in " <> name <> "\");"

-- | Substitute `result` variable in post-condition with `result` binding.
substResult :: Expr -> Expr
substResult = id  -- `result` is already bound as a let above

-- | Emit parameter list: "name: Type, name2: Type2"
emitParams :: [(Name, Type)] -> Text
emitParams = T.intercalate ", " . map (\(n, t) -> toRustIdent n <> ": " <> emitType t)

-- ---------------------------------------------------------------------------
-- Test Module
-- ---------------------------------------------------------------------------

emitTestModule :: Text -> [Statement] -> Text
emitTestModule _moduleName [] = ""
emitTestModule moduleName checks = T.unlines $
  [ "#[cfg(test)]"
  , "mod tests {"
  , "    use super::*;"
  , "    // LLMLL check blocks compiled to Rust tests"
  , "    // Install proptest for property-based testing: cargo add proptest --dev"
  , ""
  ]
  ++ map emitCheckBlock checks
  ++ [ "}" , "" ]

emitCheckBlock :: Statement -> Text
emitCheckBlock (SCheck prop) = T.unlines
  [ "    /// " <> propDescription prop
  , "    #[test]"
  , "    fn " <> sanitizeTestName (propDescription prop) <> "() {"
  , emitForAllBody prop
  , "    }"
  ]
emitCheckBlock _ = ""

emitForAllBody :: LLMLL.Syntax.Property -> Text
emitForAllBody prop =
  let bindings = propBindings prop
      body     = propBody prop
  in if null bindings
     then "        assert!(" <> emitExprInline body <> ");"
     else
       "        // for-all " <> emitBindingList bindings <> "\n"
       <> "        // proptest! { |(" <> emitForAllVars bindings <> ")| {\n"
       <> "        //     prop_assert!(" <> emitExprInline body <> ");\n"
       <> "        // }}\n"
       <> "        // TODO: enable proptest and remove this placeholder\n"
       <> "        let " <> emitLetBindings bindings <> ";\n"
       <> "        assert!(" <> emitExprInline body <> ");"

emitBindingList :: [(Name, Type)] -> Text
emitBindingList = T.intercalate ", " . map (\(n, t) -> n <> ": " <> typeLabel t)

emitForAllVars :: [(Name, Type)] -> Text
emitForAllVars = T.intercalate ", " . map (\(n, t) -> n <> ": " <> emitType t)

emitLetBindings :: [(Name, Type)] -> Text
emitLetBindings bs = T.intercalate "; let "
  [ n <> ": " <> emitType t <> " = Default::default()"
  | (n, t) <- bs
  ]

sanitizeTestName :: Text -> Text
sanitizeTestName = T.concat . map sanitizeChar . T.words . T.toLower
  where
    sanitizeChar w = T.pack $ map (\c -> if c `elem` ("abcdefghijklmnopqrstuvwxyz0123456789_" :: String) then c else '_') (T.unpack w)

-- ---------------------------------------------------------------------------
-- Type Emitter
-- ---------------------------------------------------------------------------

emitType :: Type -> Text
emitType TInt            = "i64"
emitType TFloat          = "f64"
emitType TString         = "String"
emitType TBool           = "bool"
emitType TUnit           = "()"
emitType (TBytes n)      = "[u8; " <> T.pack (show n) <> "]"
emitType (TList t)       = "Vec<" <> emitType t <> ">"
emitType (TMap k v)      = "HashMap<" <> emitType k <> ", " <> emitType v <> ">"
emitType (TResult t e)   = "Result<" <> emitType t <> ", " <> emitType e <> ">"
emitType (TFn args ret)  = "fn(" <> T.intercalate ", " (map emitType args) <> ") -> " <> emitType ret
emitType (TPromise t)    = "std::pin::Pin<Box<dyn std::future::Future<Output=" <> emitType t <> ">>>"
emitType (TDependent b _) = emitType b  -- erase dependent constraint in generated code
emitType TDelegationError = "Box<dyn std::error::Error>"
emitType (TVar n)        = "/* type var */ " <> toRustIdent n
emitType (TCustom n)     = toRustIdent n

-- ---------------------------------------------------------------------------
-- Expression Emitter
-- ---------------------------------------------------------------------------

-- | Emit an expression as a Rust expression (single line).
emitExprInline :: Expr -> Text
emitExprInline (ELit lit)         = emitLit lit
emitExprInline (EVar name)        = toRustIdent name
emitExprInline (EOp op args)      = emitOp op (map emitExprInline args)
emitExprInline (EApp func args)   =
  toRustIdent func <> "(" <> T.intercalate ", " (map emitExprInline args) <> ")"
emitExprInline (EIf cond t f)     =
  "if " <> emitExprInline cond
  <> " { " <> emitExprInline t
  <> " } else { " <> emitExprInline f <> " }"
emitExprInline (ELet bindings body) =
  "{ " <> T.intercalate " " (map emitBinding bindings) <> emitExprInline body <> " }"
  where
    emitBinding (n, _, e) = "let " <> toRustIdent n <> " = " <> emitExprInline e <> "; "
emitExprInline (EPair a b)      =
  "(" <> emitExprInline a <> ", " <> emitExprInline b <> ")"
emitExprInline (EMatch scrut cases) =
  "match " <> emitExprInline scrut <> " { "
  <> T.intercalate " " (map emitCase cases)
  <> " }"
  where
    emitCase (pat, e) = emitPat pat <> " => " <> emitExprInline e <> ","
emitExprInline (EHole hk)       =
  "todo!(\"LLMLL hole: " <> holeKindLabel' hk <> "\")"
emitExprInline (EAwait e)       = "/* await */ " <> emitExprInline e
emitExprInline (ELambda params body) =
  "|" <> T.intercalate ", " (map (\(n, t) -> toRustIdent n <> ": " <> emitType t) params)
  <> "| " <> emitExprInline body
emitExprInline (EDo steps) = emitDoSteps steps

-- | Emit expression with indentation for multi-line contexts.
emitExprIndented :: Expr -> Int -> Text
emitExprIndented expr _ = emitExprInline expr

emitDoSteps :: [DoStep] -> Text
emitDoSteps [] = "()"
emitDoSteps steps =
  "{ " <> T.intercalate "; " (map emitDoStep steps) <> " }"
  where
    emitDoStep (DoBind n e) = "let " <> toRustIdent n <> " = " <> emitExprInline e
    emitDoStep (DoExpr e)   = emitExprInline e

-- | Emit a pattern match arm.
emitPat :: Pattern -> Text
emitPat PWildcard              = "_"
emitPat (PVar n)               = toRustIdent n
emitPat (PLiteral l)           = emitLit l
emitPat (PConstructor "Success" [p]) = "Ok(" <> emitPat p <> ")"
emitPat (PConstructor "Error"   [p]) = "Err(" <> emitPat p <> ")"
emitPat (PConstructor name ps) =
  toRustIdent name <> "(" <> T.intercalate ", " (map emitPat ps) <> ")"

-- | Emit a literal value.
emitLit :: Literal -> Text
emitLit (LitInt n)    = T.pack (show n) <> "i64"
emitLit (LitFloat f)  = T.pack (show f) <> "f64"
emitLit (LitString s) = "\"" <> T.replace "\"" "\\\"" s <> "\".to_string()"
emitLit (LitBool b)   = if b then "true" else "false"
emitLit LitUnit       = "()"

-- | Emit a binary/unary operator call as Rust expression.
emitOp :: Name -> [Text] -> Text
emitOp "+"   [a, b] = "(" <> a <> " + " <> b <> ")"
emitOp "-"   [a, b] = "(" <> a <> " - " <> b <> ")"
emitOp "*"   [a, b] = "(" <> a <> " * " <> b <> ")"
emitOp "/"   [a, b] = "(" <> a <> " / " <> b <> ")"
emitOp "="   [a, b] = "(" <> a <> " == " <> b <> ")"
emitOp "!="  [a, b] = "(" <> a <> " != " <> b <> ")"
emitOp "<"   [a, b] = "(" <> a <> " < " <> b <> ")"
emitOp ">"   [a, b] = "(" <> a <> " > " <> b <> ")"
emitOp "<="  [a, b] = "(" <> a <> " <= " <> b <> ")"
emitOp ">="  [a, b] = "(" <> a <> " >= " <> b <> ")"
emitOp "and" [a, b] = "(" <> a <> " && " <> b <> ")"
emitOp "or"  [a, b] = "(" <> a <> " || " <> b <> ")"
emitOp "not" [a]    = "(!" <> a <> ")"
emitOp name  args   = name <> "(" <> T.intercalate ", " args <> ")"

holeKindLabel' :: HoleKind -> Text
holeKindLabel' (HNamed n)           = "?" <> n
holeKindLabel' (HDelegate spec)     = "?delegate @" <> delegateAgent spec
holeKindLabel' (HDelegateAsync spec) = "?delegate-async @" <> delegateAgent spec
holeKindLabel' (HChoose opts)       = "?choose " <> T.intercalate "|" opts
holeKindLabel' (HRequestCap cap)    = "?request-cap " <> cap
holeKindLabel' (HScaffold spec)     = "?scaffold " <> scaffoldTemplate spec
holeKindLabel' (HDelegatePending t) = "?pending " <> typeLabel t
holeKindLabel' HConflictResolution  = "?conflict"

-- ---------------------------------------------------------------------------
-- Utilities
-- ---------------------------------------------------------------------------

-- | Convert LLMLL identifier to a valid Rust identifier.
-- Haskell identifiers can have '-' which is illegal in Rust.
toRustIdent :: Name -> Text
toRustIdent = T.map (\c -> if c == '-' then '_' else c)

-- | Collect warnings for a statement.
stmtWarnings :: Text -> Statement -> [Text]
stmtWarnings modName (SDefLogic name _ _ _ body) =
  exprWarnings body
  where
    prefix = modName <> "::" <> name
stmtWarnings _ (SCheck prop) = exprWarnings (propBody prop)
stmtWarnings _ _ = []

exprWarnings :: Expr -> [Text]
exprWarnings (EHole (HDelegate spec)) =
  ["Unresolved delegate to @" <> delegateAgent spec <> ": will emit todo!()"]
exprWarnings (EHole (HDelegatePending t)) =
  ["Blocking delegate hole for type " <> typeLabel t <> ": will emit todo!()"]
exprWarnings (EHole HConflictResolution) =
  ["Conflict resolution hole: will emit todo!()"]
exprWarnings other = concatMap exprWarnings (subExprs other)

subExprs :: Expr -> [Expr]
subExprs (ELet bs body)    = map (\(_, _, e) -> e) bs ++ [body]
subExprs (EIf c t f)       = [c, t, f]
subExprs (EMatch e cases)  = e : map snd cases
subExprs (EApp _ args)     = args
subExprs (EOp _ args)      = args
subExprs (EPair a b)       = [a, b]
subExprs (EAwait e)        = [e]
subExprs (ELambda _ body)  = [body]
subExprs (EDo steps)       = map stepExpr steps
subExprs _                 = []

stepExpr :: DoStep -> Expr
stepExpr (DoBind _ e) = e
stepExpr (DoExpr e)   = e
