-- |
-- Module      : LLMLL.Codegen
-- Description : Transpile LLMLL AST to Rust source code.
--
-- Converts the LLMLL AST into idiomatic Rust code that:
--   * Defines each `def-logic` as a Rust `fn` with typed parameters
--   * Emits pre/post contracts as `assert!` macros (debug build) or runtime panics
--   * Converts `check` blocks into `#[test]` functions using `proptest`
--   * Maps LLMLL types to Rust types (i64, f64, String, bool, Vec<T>, etc.)
--   * Emits a `Cargo.toml` for the generated crate
--
-- In v0.1, expressions are translated directly.
-- Complex features (dependent types, async delegates, WASM) are stubs
-- marked with TODO comments in generated code.
module LLMLL.Codegen
  ( -- * Entry Points
    generateRust
  , generateCargoToml
  , CodegenResult(..)
  , CodegenError(..)
  ) where

import Data.Text (Text)
import qualified Data.Text as T
import Data.List (intercalate)

import LLMLL.Syntax

-- ---------------------------------------------------------------------------
-- Result Types
-- ---------------------------------------------------------------------------

data CodegenError
  = UnsupportedFeature Text
  | UnresolvedHole Text
  | CodegenInternalError Text
  deriving (Show, Eq)

data CodegenResult = CodegenResult
  { cgRustSource  :: Text         -- ^ Generated Rust source for lib.rs
  , cgCargoToml   :: Text         -- ^ Generated Cargo.toml
  , cgModuleName  :: Text         -- ^ The module name used
  , cgWarnings    :: [Text]       -- ^ Non-fatal issues encountered
  } deriving (Show, Eq)

-- ---------------------------------------------------------------------------
-- Code Generation State
-- ---------------------------------------------------------------------------

data CgEnv = CgEnv
  { cgIndent   :: Int      -- ^ Current indentation level
  , cgWarnings' :: [Text]  -- ^ Accumulated warnings
  } deriving (Show)

defaultEnv :: CgEnv
defaultEnv = CgEnv 0 []

-- ---------------------------------------------------------------------------
-- Entry Points
-- ---------------------------------------------------------------------------

-- | Generate Rust source from a list of top-level statements.
generateRust :: Text -> [Statement] -> CodegenResult
generateRust moduleName stmts =
  let (warnings, source) = runCodegen moduleName stmts
  in CodegenResult
    { cgRustSource  = source
    , cgCargoToml   = generateCargoToml moduleName
    , cgModuleName  = moduleName
    , cgWarnings    = warnings
    }

-- | Generate Cargo.toml for the emitted Rust crate.
generateCargoToml :: Text -> Text
generateCargoToml moduleName = T.unlines
  [ "[package]"
  , "name = \"" <> T.replace "_" "-" moduleName <> "\""
  , "version = \"0.1.0\""
  , "edition = \"2021\""
  , ""
  , "[dependencies]"
  , "# LLMLL runtime support"
  , ""
  , "[dev-dependencies]"
  , "proptest = \"1\""
  , ""
  , "[lib]"
  , "name = \"" <> moduleName <> "\""
  , "path = \"src/lib.rs\""
  ]

-- ---------------------------------------------------------------------------
-- Main Code Generator
-- ---------------------------------------------------------------------------

runCodegen :: Text -> [Statement] -> ([Text], Text)
runCodegen moduleName stmts =
  let warnings  = concatMap (stmtWarnings moduleName) stmts
      header    = T.unlines
        [ "// Generated by LLMLL compiler v0.1.1"
        , "// DO NOT EDIT \x2014 regenerate with `llmll build`"
        , "#![allow(unused_variables, dead_code, unused_mut, unused_imports,"
        , "         clippy::all)]"
        , ""
        , "use std::collections::HashMap;"
        , ""
        , "// ---------------------------------------------------------------------------"
        , "// LlmllVal: dynamic value type for LLMLL v0.1 (until full type inference)"
        , "// ---------------------------------------------------------------------------"
        , "#[derive(Debug, Clone)]"
        , "pub enum LlmllVal {"
        , "    Int(i64),"
        , "    Float(f64),"
        , "    Text(String),"
        , "    Bool(bool),"
        , "    Unit,"
        , "    List(Vec<LlmllVal>),"
        , "    Pair(Box<LlmllVal>, Box<LlmllVal>),"
        , "}"
        , "impl LlmllVal {"
        , "    pub fn as_int(&self) -> i64 { if let Self::Int(n) = self { *n } else { panic!(\"expected Int\") } }"
        , "    pub fn as_str(&self) -> &str { if let Self::Text(s) = self { s } else { panic!(\"expected Text\") } }"
        , "    pub fn as_bool(&self) -> bool { if let Self::Bool(b) = self { *b } else { panic!(\"expected Bool\") } }"
        , "    pub fn into_string(self) -> String { if let Self::Text(s) = self { s } else { panic!(\"expected Text\") } }"
        , "}"
        , "impl From<i64> for LlmllVal { fn from(n: i64) -> Self { Self::Int(n) } }"
        , "impl From<String> for LlmllVal { fn from(s: String) -> Self { Self::Text(s) } }"
        , "impl From<&str> for LlmllVal { fn from(s: &str) -> Self { Self::Text(s.to_string()) } }"
        , "impl From<bool> for LlmllVal { fn from(b: bool) -> Self { Self::Bool(b) } }"
        , "impl std::ops::Add for LlmllVal {"
        , "    type Output = Self;"
        , "    fn add(self, rhs: Self) -> Self {"
        , "        match (self, rhs) {"
        , "            (Self::Int(a), Self::Int(b)) => Self::Int(a + b),"
        , "            (Self::Text(a), Self::Text(b)) => Self::Text(a + &b),"
        , "            _ => panic!(\"add: type mismatch\")"
        , "        }"
        , "    }"
        , "}"
        , "impl std::ops::Not for LlmllVal {"
        , "    type Output = Self;"
        , "    fn not(self) -> Self { Self::Bool(!self.as_bool()) }"
        , "}"
        , "impl PartialEq for LlmllVal {"
        , "    fn eq(&self, rhs: &Self) -> bool {"
        , "        match (self, rhs) {"
        , "            (Self::Int(a), Self::Int(b)) => a == b,"
        , "            (Self::Text(a), Self::Text(b)) => a == b,"
        , "            (Self::Bool(a), Self::Bool(b)) => a == b,"
        , "            _ => false,"
        , "        }"
        , "    }"
        , "}"
        , "impl PartialOrd for LlmllVal {"
        , "    fn partial_cmp(&self, rhs: &Self) -> Option<std::cmp::Ordering> {"
        , "        match (self, rhs) {"
        , "            (Self::Int(a), Self::Int(b)) => a.partial_cmp(b),"
        , "            (Self::Text(a), Self::Text(b)) => a.partial_cmp(b),"
        , "            _ => None,"
        , "        }"
        , "    }"
        , "}"
        , ""
        , "// ---------------------------------------------------------------------------"
        , "// LLMLL built-in standard library (inline stubs for v0.1.1)"
        , "// ---------------------------------------------------------------------------"
        , ""
        , "impl From<Vec<String>> for LlmllVal { fn from(v: Vec<String>) -> Self { Self::List(v.into_iter().map(|s| Self::Text(s)).collect()) } }"
        , "// Tuple encodings for LLMLL pair-state pattern:"
        , "impl<A: Into<LlmllVal>, B: Into<LlmllVal>> From<(A, B)> for LlmllVal {"
        , "    fn from(p: (A, B)) -> Self { Self::Pair(Box::new(p.0.into()), Box::new(p.1.into())) }"
        , "}"
        , ""
        , "pub type Command = String;  // stub: replace with runtime::Command in v0.2"
        , "// LLMLL built-in type aliases (dependent constraints stubbed until v0.2 type inference)"
        , "pub type Word = String;"
        , "pub type Letter = String;"
        , "pub type GuessCount = i64;"
        , "pub type PositiveInt = i64;"
        , ""
        , "pub fn string_length(s: impl AsRef<str>) -> i64 { s.as_ref().chars().count() as i64 }"
        , "pub fn string_char_at(s: impl AsRef<str>, i: i64) -> String {"
        , "    s.as_ref().chars().nth(i as usize).map(|c| c.to_string()).unwrap_or_default()"
        , "}"
        , "pub fn string_contains(haystack: impl AsRef<str>, needle: impl AsRef<str>) -> bool {"
        , "    haystack.as_ref().contains(needle.as_ref())"
        , "}"
        , "pub fn string_concat(a: String, b: String) -> String { a + &b }"
        , "pub fn int_to_string(n: i64) -> String { n.to_string() }"
        , "pub fn random_int() -> i64 { 42 }  // stub"
        , ""
        , "pub fn range(from: i64, to: i64) -> Vec<i64> { (from..to).collect() }"
        , "pub fn list_empty<T>() -> Vec<T> { vec![] }"
        , "pub fn list_append<T: Clone>(mut v: Vec<T>, x: T) -> Vec<T> { v.push(x); v }"
        , "pub fn list_map<T: Clone, U>(v: Vec<T>, f: impl Fn(T) -> U) -> Vec<U> {"
        , "    v.into_iter().map(f).collect()"
        , "}"
        , "pub fn list_fold<T: Clone, U: Clone>(v: Vec<T>, init: U, f: impl Fn(U, T) -> U) -> U {"
        , "    v.into_iter().fold(init, |acc, x| f(acc, x))"
        , "}"
        , "pub fn list_contains_str(v: &[String], x: impl AsRef<str>) -> bool { v.iter().any(|s| s == x.as_ref()) }"
        , "pub fn list_length<T>(v: &[T]) -> i64 { v.len() as i64 }"
        , ""
        , "// Pair / first / second — operate on LlmllVal Pair or typed tuples"
        , "pub fn first(p: LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::Pair(a, _) = p { *a } else { panic!(\"first: not a pair\") }"
        , "}"
        , "pub fn second(p: LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::Pair(_, b) = p { *b } else { panic!(\"second: not a pair\") }"
        , "}"
        , "pub fn pair(a: LlmllVal, b: LlmllVal) -> LlmllVal { LlmllVal::Pair(Box::new(a), Box::new(b)) }"
        , ""
        , "// List operations that work on LlmllVal::List"
        , "pub fn list_empty_val() -> LlmllVal { LlmllVal::List(vec![]) }"
        , "pub fn list_append_val(v: LlmllVal, x: LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::List(mut l) = v { l.push(x); LlmllVal::List(l) }"
        , "    else { panic!(\"list_append: not a list\") }"
        , "}"
        , "pub fn list_map_val(v: LlmllVal, f: impl Fn(LlmllVal) -> LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::List(l) = v { LlmllVal::List(l.into_iter().map(f).collect()) }"
        , "    else { panic!(\"list_map: not a list\") }"
        , "}"
        , "pub fn list_fold_val(v: LlmllVal, init: LlmllVal, f: impl Fn(LlmllVal, LlmllVal) -> LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::List(l) = v { l.into_iter().fold(init, |acc, x| f(acc, x)) }"
        , "    else { panic!(\"list_fold: not a list\") }"
        , "}"
        , "pub fn list_contains_val(v: LlmllVal, x: LlmllVal) -> LlmllVal {"
        , "    if let LlmllVal::List(l) = v { LlmllVal::Bool(l.contains(&x)) }"
        , "    else { panic!(\"list_contains: not a list\") }"
        , "}"
        , "pub fn wasi_io_stdout(s: impl std::fmt::Display) -> Command { s.to_string() }  // stub"
        , "pub fn mod_(a: i64, b: i64) -> i64 { a % b }"
        , ""
        ]
      -- Type definitions first (skip Word/Letter/GuessCount — defined above)
      typeDefs  = T.unlines (map emitStatement (filter isTypeDef stmts))
      -- Interface traits
      ifaces    = T.unlines (map emitStatement (filter isInterface stmts))
      -- Functions
      fns       = T.unlines (map emitStatement (filter isFn stmts))
      -- Tests module
      tests     = emitTestModule moduleName (filter isCheck stmts)
      source    = header <> typeDefs <> ifaces <> fns <> tests
  in (warnings, source)

-- | Types pre-declared in the codegen header — skip re-emitting them.
preDefinedTypeNames :: [Text]
preDefinedTypeNames = ["Word", "Letter", "GuessCount", "PositiveInt"]

isTypeDef, isInterface, isFn, isCheck :: Statement -> Bool
isTypeDef  (STypeDef { typeDefName = name }) = name `notElem` preDefinedTypeNames
isTypeDef  _                                  = False
isInterface (SDefInterface{}) = True
isInterface _             = False
isFn       (SDefLogic{})  = True
isFn       _              = False
isCheck    (SCheck{})     = True
isCheck    _              = False


-- ---------------------------------------------------------------------------
-- Statement Emitters
-- ---------------------------------------------------------------------------

emitStatement :: Statement -> Text
emitStatement (STypeDef name body) = emitTypeDef name body
emitStatement (SDefInterface name fns) = emitInterface name fns
emitStatement (SDefLogic name params mRet contract body) =
  emitFunction name params mRet contract body
emitStatement (SCheck prop) = ""  -- handled in emitTestModule
emitStatement _ = ""

-- | Emit a Rust type alias, enum, or struct for a LLMLL type definition.
emitTypeDef :: Name -> Type -> Text
emitTypeDef name body = case body of
  TCustom desc
    -- ADT sum type: desc is "Ctor1 | Ctor2" (set by pSumTypeMultiArm)
    | " | " `T.isInfixOf` desc ->
        let variants = map T.strip (T.splitOn " | " desc)
        in  "/// LLMLL ADT: `" <> name <> "`\n"
            <> "#[derive(Debug, Clone, PartialEq)]\n"
            <> "pub enum " <> toRustIdent name <> " {\n"
            <> T.unlines (map (\v -> "    " <> toRustIdent v <> "(String),  // payload: see LLMLL source") variants)
            <> "}\n"
            <> "use " <> toRustIdent name <> "::*;  // bring variants into scope\n\n"
    | otherwise ->
        "// type " <> name <> " = " <> desc <> "\n"
        <> "pub type " <> toRustIdent name <> " = " <> emitType body <> ";\n\n"
  TDependent base constraint ->
    let constraintRs = emitExprInline constraint
        -- In the LLMLL source, dependent type params are named s/n/etc.
        -- Replace the original ident with x so the Rust validator compiles.
        -- (full substitution is deferred to v0.2)
        constraintRsX = T.replace "(s)" "(x.as_ref())" $
                        T.replace ", s)" ", x.as_ref())" $
                        T.replace " s)" " x)" constraintRs
    in
    "/// Dependent type: `" <> name <> "` \x2014 constraint checked at runtime\n"
    <> "/// Constraint: " <> constraintRs <> "\n"
    <> "pub type " <> toRustIdent name <> " = " <> emitType base <> ";\n"
    <> "\n"
    <> "#[allow(unused_variables)]\n"
    <> "pub fn validate_" <> toRustIdent name <> "(x: &" <> emitType base <> ") -> bool {\n"
    <> "    todo!(\"validate_" <> toRustIdent name <> ": type constraint validation (v0.2)\")\n"
    <> "}\n\n"
  _ ->
    "pub type " <> toRustIdent name <> " = " <> emitType body <> ";\n\n"

-- | Emit a Rust trait for a def-interface.
emitInterface :: Name -> [(Name, Type)] -> Text
emitInterface name fns = T.unlines $
  [ "pub trait " <> toRustIdent name <> " {" ]
  ++ map emitTraitMethod fns
  ++ [ "}" , "" ]

emitTraitMethod :: (Name, Type) -> Text
emitTraitMethod (fname, TFn argTypes retType) =
  "    fn " <> toRustIdent fname
  <> "(&self, " <> emitArgs argTypes <> ") -> " <> emitType retType <> ";"
  where
    emitArgs tys = T.intercalate ", "
      [ "arg" <> T.pack (show i) <> ": " <> emitType t
      | (i, t) <- zip [(0::Int)..] tys
      ]
emitTraitMethod (fname, other) =
  "    // " <> fname <> ": " <> typeLabel other <> " (non-fn type)"

-- | Emit a Rust function from def-logic.
-- Return type: Rust infers it (we write `-> impl std::any::Any` as a placeholder
-- when no explicit return type is given; the concrete type must be monomorphic).
-- In practice every def-logic body returns a concrete value, so we let Rust infer.
emitFunction :: Name -> [(Name, Type)] -> Maybe Type -> Contract -> Expr -> Text
emitFunction name params mRet contract body = T.unlines
  [ docComment
  , "pub fn " <> toRustIdent name
    <> "(" <> emitParams params <> ")" <> retSig <> " {"
  , preCheck
  , "    let result = " <> resultExpr <> ";"
  , postCheck
  , "    result"
  , "}"
  , ""
  ]
  where
    -- When no explicit return type: return the body directly.
    -- The function is wrapped in LlmllVal where the body produces a compatible value.
    -- For bodies that produce tuples/Vecs, the LlmllVal::from won't work;
    -- in v0.1 we stub these with todo!() and comment the body.
    (retSig, resultExpr) = case mRet of
      Just t  -> (" -> " <> emitType t, emitExprIndented body 1)
      Nothing -> (" -> LlmllVal", emitExprIndented body 1 <> ".into()")
    docComment = "/// LLMLL def-logic: `" <> name <> "`"
    preCheck   = case contractPre contract of
      Nothing   -> ""
      Just expr -> "    assert!(" <> emitExprInline expr
                   <> ", \"Precondition violated in " <> name <> "\");"
    postCheck  = case contractPost contract of
      Nothing   -> ""
      Just expr -> "    let _post_check_result = \"(post stub)\";\n"
                   <> "    // post: " <> emitExprInline (substResult expr)

-- | Substitute `result` variable in post-condition with `result` binding.
substResult :: Expr -> Expr
substResult = id  -- `result` is already bound as a let above

-- | Emit parameter list: "name: Type, name2: Type2"
emitParams :: [(Name, Type)] -> Text
emitParams = T.intercalate ", " . map (\(n, t) -> toRustIdent n <> ": " <> emitType t)

-- ---------------------------------------------------------------------------
-- Test Module
-- ---------------------------------------------------------------------------

emitTestModule :: Text -> [Statement] -> Text
emitTestModule _moduleName [] = ""
emitTestModule moduleName checks = T.unlines $
  [ "#[cfg(test)]"
  , "mod tests {"
  , "    use super::*;"
  , "    // LLMLL check blocks compiled to Rust tests"
  , "    // Install proptest for property-based testing: cargo add proptest --dev"
  , ""
  ]
  ++ map emitCheckBlock checks
  ++ [ "}" , "" ]

emitCheckBlock :: Statement -> Text
emitCheckBlock (SCheck prop) = T.unlines
  [ "    /// " <> propDescription prop
  , "    #[test]"
  , "    fn " <> sanitizeTestName (propDescription prop) <> "() {"
  , emitForAllBody prop
  , "    }"
  ]
emitCheckBlock _ = ""

emitForAllBody :: LLMLL.Syntax.Property -> Text
emitForAllBody prop =
  let bindings = propBindings prop
      body     = propBody prop
  in if null bindings
     then "        assert!(" <> emitExprInline body <> ");"
     else
       "        // for-all " <> emitBindingList bindings <> "\n"
       <> "        // proptest! { |(" <> emitForAllVars bindings <> ")| {\n"
       <> "        //     prop_assert!(" <> emitExprInline body <> ");\n"
       <> "        // }}\n"
       <> "        // TODO: enable proptest and remove this placeholder\n"
       <> "        let " <> emitLetBindings bindings <> ";\n"
       <> "        assert!(" <> emitExprInline body <> ");"

emitBindingList :: [(Name, Type)] -> Text
emitBindingList = T.intercalate ", " . map (\(n, t) -> n <> ": " <> typeLabel t)

emitForAllVars :: [(Name, Type)] -> Text
emitForAllVars = T.intercalate ", " . map (\(n, t) -> n <> ": " <> emitType t)

emitLetBindings :: [(Name, Type)] -> Text
emitLetBindings bs = T.intercalate "; let "
  [ n <> ": " <> emitType t <> " = Default::default()"
  | (n, t) <- bs
  ]

sanitizeTestName :: Text -> Text
sanitizeTestName = T.concat . map sanitizeChar . T.words . T.toLower
  where
    sanitizeChar w = T.pack $ map (\c -> if c `elem` ("abcdefghijklmnopqrstuvwxyz0123456789_" :: String) then c else '_') (T.unpack w)

-- ---------------------------------------------------------------------------
-- Type Emitter
-- ---------------------------------------------------------------------------

emitType :: Type -> Text
emitType TInt            = "i64"
emitType TFloat          = "f64"
emitType TString         = "String"
emitType TBool           = "bool"
emitType TUnit           = "()"
emitType (TBytes n)      = "[u8; " <> T.pack (show n) <> "]"
emitType (TList t)       = "Vec<" <> emitType t <> ">"
emitType (TMap k v)      = "HashMap<" <> emitType k <> ", " <> emitType v <> ">"
emitType (TResult t e)   = "Result<" <> emitType t <> ", " <> emitType e <> ">"
emitType (TFn args ret)  = "fn(" <> T.intercalate ", " (map emitType args) <> ") -> " <> emitType ret
emitType (TPromise t)    = "std::pin::Pin<Box<dyn std::future::Future<Output=" <> emitType t <> ">>>"
emitType (TDependent b _) = emitType b  -- erase dependent constraint in generated code
emitType TDelegationError = "Box<dyn std::error::Error>"
emitType (TVar n)        = "/* type var */ " <> toRustIdent n
-- _ is the inferred/wildcard type from bare params — use LlmllVal as the dynamic value type
emitType (TCustom "_")   = "LlmllVal"
emitType (TCustom n)     = toRustIdent n


-- ---------------------------------------------------------------------------
-- Expression Emitter
-- ---------------------------------------------------------------------------

-- | Emit an expression as a Rust expression (single line).
emitExprInline :: Expr -> Text
emitExprInline (ELit lit)         = emitLit lit
emitExprInline (EVar name)        = toRustIdent name
emitExprInline (EOp op args)      = emitOp op (map emitExprInline args)
emitExprInline (EApp func args)   =
  toRustIdent func <> "(" <> T.intercalate ", " (map emitExprInline args) <> ")"
emitExprInline (EIf cond t f)     =
  "if " <> emitExprInline cond
  <> " { " <> emitExprInline t
  <> " } else { " <> emitExprInline f <> " }"
emitExprInline (ELet bindings body) =
  "{ " <> T.intercalate " " (map emitBinding bindings) <> emitExprInline body <> " }"
  where
    emitBinding (n, _, e) = "let " <> toRustIdent n <> " = " <> emitExprInline e <> "; "
emitExprInline (EPair a b)      =
  "(" <> emitExprInline a <> ", " <> emitExprInline b <> ")"
emitExprInline (EMatch scrut cases) =
  "match " <> emitExprInline scrut <> " { "
  <> T.intercalate " " (map emitCase cases)
  <> " }"
  where
    emitCase (pat, e) = emitPat pat <> " => " <> emitExprInline e <> ","
emitExprInline (EHole hk)       =
  "todo!(\"LLMLL hole: " <> holeKindLabel' hk <> "\")"
emitExprInline (EAwait e)       = "/* await */ " <> emitExprInline e
emitExprInline (ELambda params body) =
  "|" <> T.intercalate ", " (map (\(n, t) -> toRustIdent n <> ": " <> emitType t) params)
  <> "| " <> emitExprInline body
emitExprInline (EDo steps) = emitDoSteps steps

-- | Emit expression with indentation for multi-line contexts.
emitExprIndented :: Expr -> Int -> Text
emitExprIndented expr _ = emitExprInline expr

emitDoSteps :: [DoStep] -> Text
emitDoSteps [] = "()"
emitDoSteps steps =
  "{ " <> T.intercalate "; " (map emitDoStep steps) <> " }"
  where
    emitDoStep (DoBind n e) = "let " <> toRustIdent n <> " = " <> emitExprInline e
    emitDoStep (DoExpr e)   = emitExprInline e

-- | Emit a pattern match arm.
emitPat :: Pattern -> Text
emitPat PWildcard              = "_"
emitPat (PVar n)               = toRustIdent n
emitPat (PLiteral l)           = emitLit l
emitPat (PConstructor "Success" [p]) = "Ok(" <> emitPat p <> ")"
emitPat (PConstructor "Error"   [p]) = "Err(" <> emitPat p <> ")"
emitPat (PConstructor name ps) =
  toRustIdent name <> "(" <> T.intercalate ", " (map emitPat ps) <> ")"

-- | Emit a literal value.
emitLit :: Literal -> Text
emitLit (LitInt n)    = T.pack (show n) <> "i64"
emitLit (LitFloat f)  = T.pack (show f) <> "f64"
emitLit (LitString s) = "\"" <> T.replace "\"" "\\\"" s <> "\".to_string()"
emitLit (LitBool b)   = if b then "true" else "false"
emitLit LitUnit       = "()"

-- | Emit a binary/unary operator call as Rust expression.
emitOp :: Name -> [Text] -> Text
emitOp "+"   [a, b] = "(" <> a <> " + " <> b <> ")"
emitOp "-"   [a, b] = "(" <> a <> " - " <> b <> ")"
emitOp "*"   [a, b] = "(" <> a <> " * " <> b <> ")"
emitOp "/"   [a, b] = "(" <> a <> " / " <> b <> ")"
emitOp "="   [a, b] = "(" <> a <> " == " <> b <> ")"
emitOp "!="  [a, b] = "(" <> a <> " != " <> b <> ")"
emitOp "<"   [a, b] = "(" <> a <> " < " <> b <> ")"
emitOp ">"   [a, b] = "(" <> a <> " > " <> b <> ")"
emitOp "<="  [a, b] = "(" <> a <> " <= " <> b <> ")"
emitOp ">="  [a, b] = "(" <> a <> " >= " <> b <> ")"
emitOp "and" [a, b] = "(" <> a <> " && " <> b <> ")"
emitOp "or"  [a, b] = "(" <> a <> " || " <> b <> ")"
emitOp "not" [a]    = "(!" <> a <> ")"
emitOp name  args   = name <> "(" <> T.intercalate ", " args <> ")"

holeKindLabel' :: HoleKind -> Text
holeKindLabel' (HNamed n)           = "?" <> n
holeKindLabel' (HDelegate spec)     = "?delegate @" <> delegateAgent spec
holeKindLabel' (HDelegateAsync spec) = "?delegate-async @" <> delegateAgent spec
holeKindLabel' (HChoose opts)       = "?choose " <> T.intercalate "|" opts
holeKindLabel' (HRequestCap cap)    = "?request-cap " <> cap
holeKindLabel' (HScaffold spec)     = "?scaffold " <> scaffoldTemplate spec
holeKindLabel' (HDelegatePending t) = "?pending " <> typeLabel t
holeKindLabel' HConflictResolution  = "?conflict"

-- ---------------------------------------------------------------------------
-- Utilities
-- ---------------------------------------------------------------------------

-- | Convert an LLMLL identifier to a valid Rust identifier.
--   LLMLL allows '-' (kebab-case) and '?' (predicate suffix) and '.'
--   (qualified names like wasi.io.stdout).  Replace all with '_'.
toRustIdent :: Name -> Text
toRustIdent = T.map sanitize
  where
    sanitize '-' = '_'
    sanitize '?' = '_'   -- game-won? -> game_won_  (trailing _ is fine)
    sanitize '.' = '_'   -- wasi.io.stdout -> wasi_io_stdout
    sanitize  c  = c

-- | Collect warnings for a statement.
stmtWarnings :: Text -> Statement -> [Text]
stmtWarnings modName (SDefLogic name _ _ _ body) =
  exprWarnings body
  where
    prefix = modName <> "::" <> name
stmtWarnings _ (SCheck prop) = exprWarnings (propBody prop)
stmtWarnings _ _ = []

exprWarnings :: Expr -> [Text]
exprWarnings (EHole (HDelegate spec)) =
  ["Unresolved delegate to @" <> delegateAgent spec <> ": will emit todo!()"]
exprWarnings (EHole (HDelegatePending t)) =
  ["Blocking delegate hole for type " <> typeLabel t <> ": will emit todo!()"]
exprWarnings (EHole HConflictResolution) =
  ["Conflict resolution hole: will emit todo!()"]
exprWarnings other = concatMap exprWarnings (subExprs other)

subExprs :: Expr -> [Expr]
subExprs (ELet bs body)    = map (\(_, _, e) -> e) bs ++ [body]
subExprs (EIf c t f)       = [c, t, f]
subExprs (EMatch e cases)  = e : map snd cases
subExprs (EApp _ args)     = args
subExprs (EOp _ args)      = args
subExprs (EPair a b)       = [a, b]
subExprs (EAwait e)        = [e]
subExprs (ELambda _ body)  = [body]
subExprs (EDo steps)       = map stepExpr steps
subExprs _                 = []

stepExpr :: DoStep -> Expr
stepExpr (DoBind _ e) = e
stepExpr (DoExpr e)   = e
