// Generated by LLMLL compiler v0.1.1 (DYNAMIC_RUNTIME)
// DO NOT EDIT — regenerate with `llmll build`
#![allow(unused_variables, dead_code, unused_mut, unused_imports, clippy::all)]

pub mod ffi;

use crate::ffi::env::*;
use crate::ffi::todo_json::*;
use crate::ffi::atomic_fs::*;
use crate::ffi::timer::*;

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// LlmllVal: dynamic value type for LLMLL v0.1
// ---------------------------------------------------------------------------
#[derive(Debug, Clone, PartialEq)]
pub enum LlmllVal {
    Int(i64),
    Float(f64),
    Text(String),
    Bool(bool),
    Unit,
    List(Vec<LlmllVal>),
    Pair(Box<LlmllVal>, Box<LlmllVal>),
    Adt(String, Vec<LlmllVal>),
}

impl LlmllVal {
    pub fn as_int(&self) -> i64 { if let Self::Int(n) = self { *n } else { panic!("expected Int") } }
    pub fn as_str(&self) -> &str { if let Self::Text(s) = self { s } else { panic!("expected Text") } }
    pub fn as_bool(&self) -> bool { if let Self::Bool(b) = self { *b } else { panic!("expected Bool") } }
    pub fn into_string(self) -> String { if let Self::Text(s) = self { s } else { panic!("expected Text") } }
}

impl std::fmt::Display for LlmllVal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Int(n) => write!(f, "{}", n),
            Self::Float(n) => write!(f, "{}", n),
            Self::Text(s) => write!(f, "{}", s),
            Self::Bool(b) => write!(f, "{}", b),
            Self::Unit => write!(f, "()"),
            Self::List(l) => write!(f, "{:?}", l),
            Self::Pair(a, b) => write!(f, "({}, {})", a, b),
            Self::Adt(c, args) => write!(f, "{}({:?})", c, args),
        }
    }
}

impl From<i64> for LlmllVal { fn from(n: i64) -> Self { Self::Int(n) } }
impl From<String> for LlmllVal { fn from(s: String) -> Self { Self::Text(s) } }
impl From<&str> for LlmllVal { fn from(s: &str) -> Self { Self::Text(s.to_string()) } }
impl From<bool> for LlmllVal { fn from(b: bool) -> Self { Self::Bool(b) } }
impl<A: Into<LlmllVal>, B: Into<LlmllVal>> From<(A, B)> for LlmllVal {
    fn from(p: (A, B)) -> Self { Self::Pair(Box::new(p.0.into()), Box::new(p.1.into())) }
}

impl std::ops::Add for LlmllVal {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Int(a), Self::Int(b)) => Self::Int(a + b),
            (Self::Text(a), Self::Text(b)) => Self::Text(a + &b),
            _ => panic!("add: type mismatch")
        }
    }
}

impl std::ops::Not for LlmllVal {
    type Output = Self;
    fn not(self) -> Self { Self::Bool(!self.as_bool()) }
}

impl PartialOrd for LlmllVal {
    fn partial_cmp(&self, rhs: &Self) -> Option<std::cmp::Ordering> {
        match (self, rhs) {
            (Self::Int(a), Self::Int(b)) => a.partial_cmp(b),
            (Self::Text(a), Self::Text(b)) => a.partial_cmp(b),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// LLMLL built-in standard library
// ---------------------------------------------------------------------------
pub type Command = LlmllVal;
pub type Word = LlmllVal;
pub type Letter = LlmllVal;
pub type GuessCount = LlmllVal;
pub type PositiveInt = LlmllVal;

pub fn string_length(s: LlmllVal) -> LlmllVal { LlmllVal::Int(s.as_str().chars().count() as i64) }
pub fn string_char_at(s: LlmllVal, i: LlmllVal) -> LlmllVal {
    LlmllVal::Text(s.as_str().chars().nth(i.as_int() as usize).map(|c| c.to_string()).unwrap_or_default())
}
pub fn string_contains(haystack: LlmllVal, needle: LlmllVal) -> LlmllVal {
    LlmllVal::Bool(haystack.as_str().contains(needle.as_str()))
}
pub fn string_concat(a: LlmllVal, b: LlmllVal) -> LlmllVal { LlmllVal::Text(a.as_str().to_owned() + b.as_str()) }
pub fn int_to_string(n: LlmllVal) -> LlmllVal { LlmllVal::Text(n.as_int().to_string()) }
pub fn random_int() -> LlmllVal { LlmllVal::Int(42) }
pub fn range(from: LlmllVal, to: LlmllVal) -> LlmllVal {
    LlmllVal::List((from.as_int()..to.as_int()).map(LlmllVal::Int).collect())
}
pub fn list_empty() -> LlmllVal { LlmllVal::List(vec![]) }
pub fn list_append(v: LlmllVal, x: LlmllVal) -> LlmllVal {
    if let LlmllVal::List(mut l) = v { l.push(x); LlmllVal::List(l) } else { panic!("list_append: not a list") }
}
pub fn list_map(v: LlmllVal, f: impl Fn(LlmllVal) -> LlmllVal) -> LlmllVal {
    if let LlmllVal::List(l) = v { LlmllVal::List(l.into_iter().map(f).collect()) } else { panic!("list_map: not a list") }
}
pub fn list_fold(v: LlmllVal, init: LlmllVal, f: impl Fn(LlmllVal, LlmllVal) -> LlmllVal) -> LlmllVal {
    if let LlmllVal::List(l) = v { l.into_iter().fold(init, |acc, x| f(acc, x)) } else { panic!("list_fold: not a list") }
}
pub fn list_contains(v: LlmllVal, x: LlmllVal) -> LlmllVal {
    if let LlmllVal::List(l) = v { LlmllVal::Bool(l.contains(&x)) } else { panic!("list_contains: not a list") }
}
pub fn list_length(v: LlmllVal) -> LlmllVal {
    if let LlmllVal::List(l) = v { LlmllVal::Int(l.len() as i64) } else { panic!("list_length: not a list") }
}
pub fn first(p: LlmllVal) -> LlmllVal {
    if let LlmllVal::Pair(a, _) = p { *a } else { panic!("first: not a pair") }
}
pub fn second(p: LlmllVal) -> LlmllVal {
    if let LlmllVal::Pair(_, b) = p { *b } else { panic!("second: not a pair") }
}
pub fn pair(a: LlmllVal, b: LlmllVal) -> LlmllVal { LlmllVal::Pair(Box::new(a), Box::new(b)) }
pub fn wasi_io_stdout(s: LlmllVal) -> Command { s }
pub fn wasi_io_stdout_str(s: &str) -> Command { LlmllVal::Text(s.to_string()) }
pub fn mod_(a: LlmllVal, b: LlmllVal) -> LlmllVal { LlmllVal::Int(a.as_int() % b.as_int()) }

// ---------------------------------------------------------------------------
// §13 standard library — string / Result helpers
// ---------------------------------------------------------------------------
pub fn string_slice(s: LlmllVal, start: LlmllVal, end: LlmllVal) -> LlmllVal {
    let st = start.as_int() as usize;
    let en = end.as_int() as usize;
    LlmllVal::Text(s.as_str().chars().skip(st).take(en.saturating_sub(st)).collect())
}
pub fn string_to_int(s: LlmllVal) -> LlmllVal {
    match s.as_str().trim().parse::<i64>() {
        Ok(n)  => LlmllVal::Adt("Success".to_string(), vec![LlmllVal::Int(n)]),
        Err(e) => LlmllVal::Adt("Error".to_string(),   vec![LlmllVal::Text(e.to_string())]),
    }
}
pub fn ok(v: LlmllVal) -> LlmllVal { LlmllVal::Adt("Success".to_string(), vec![v]) }
pub fn err(e: LlmllVal) -> LlmllVal { LlmllVal::Adt("Error".to_string(),   vec![e]) }
pub fn is_ok(r: LlmllVal) -> LlmllVal {
    match &r { LlmllVal::Adt(c, _) => LlmllVal::Bool(c == "Success"), _ => LlmllVal::Bool(false) }
}
pub fn unwrap(r: LlmllVal) -> LlmllVal {
    match r { LlmllVal::Adt(ref c, ref v) if c == "Success" => v[0].clone(),
              _ => panic!("unwrap called on Error") }
}
pub fn unwrap_or(r: LlmllVal, default: LlmllVal) -> LlmllVal {
    match r { LlmllVal::Adt(ref c, ref v) if c == "Success" => v[0].clone(),
              _ => default }
}
pub fn seq_commands(a: LlmllVal, b: LlmllVal) -> LlmllVal {
    if let (LlmllVal::Text(t1), LlmllVal::Text(t2)) = (&a, &b) {
        LlmllVal::Text(format!("{}{}", t1, t2))
    } else {
        panic!("seq-commands: expected Text commands")
    }
}

// Generic FFI helpers — used by src/ffi/**/*.rs
pub fn llmll_to_str(v: &LlmllVal) -> String { v.as_str().to_string() }
pub fn llmll_to_i64(v: &LlmllVal) -> i64    { v.as_int() }
pub fn llmll_to_bool(v: &LlmllVal) -> bool  { v.as_bool() }
pub fn str_to_llmll(s: String)    -> LlmllVal { LlmllVal::Text(s) }
pub fn i64_to_llmll(i: i64)       -> LlmllVal { LlmllVal::Int(i) }
pub fn bool_to_llmll(b: bool)     -> LlmllVal { LlmllVal::Bool(b) }

// ---------------------------------------------------------------------------
// Arithmetic operator traits — Sub, Mul, Div (mirror Add above)
// ---------------------------------------------------------------------------
impl std::ops::Sub for LlmllVal {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Int(a),   Self::Int(b))   => Self::Int(a - b),
            (Self::Float(a), Self::Float(b)) => Self::Float(a - b),
            _ => panic!("sub: type mismatch")
        }
    }
}
impl std::ops::Mul for LlmllVal {
    type Output = Self;
    fn mul(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Int(a),   Self::Int(b))   => Self::Int(a * b),
            (Self::Float(a), Self::Float(b)) => Self::Float(a * b),
            _ => panic!("mul: type mismatch")
        }
    }
}
impl std::ops::Div for LlmllVal {
    type Output = Self;
    fn div(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Self::Int(a),   Self::Int(b))   => Self::Int(a / b),
            (Self::Float(a), Self::Float(b)) => Self::Float(a / b),
            _ => panic!("div: type mismatch")
        }
    }
}

pub type HttpMethod = LlmllVal;


pub type HttpRequest = LlmllVal;


pub type HttpResponse = LlmllVal;


pub type Task = LlmllVal;


pub type TaskInput = LlmllVal;


pub type AppState = LlmllVal;


pub fn task_id(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((unwrap_task((t).clone())).clone())).clone());
    result
}

pub fn task_title(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((second((unwrap_task((t).clone())).clone())).clone())).clone());
    result
}

pub fn task_completed(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((second((second((unwrap_task((t).clone())).clone())).clone())).clone())).clone());
    result
}

pub fn task_priority(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((second((second((second((unwrap_task((t).clone())).clone())).clone())).clone())).clone())).clone());
    result
}

pub fn task_created(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((second((second((second((second((unwrap_task((t).clone())).clone())).clone())).clone())).clone())).clone())).clone());
    result
}

pub fn task_completed_date(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((second((second((second((second((second((unwrap_task((t).clone())).clone())).clone())).clone())).clone())).clone())).clone());
    result
}

pub fn unwrap_task(t: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((t).clone());
    result
}

pub fn make_task(id: LlmllVal, title: LlmllVal, comp: LlmllVal, prio: LlmllVal, cred: LlmllVal, comp_date: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((LlmllVal::from(((id).clone(), (LlmllVal::from(((title).clone(), (LlmllVal::from(((comp).clone(), (LlmllVal::from(((prio).clone(), (LlmllVal::from(((cred).clone(), (comp_date).clone()))).clone()))).clone()))).clone()))).clone()))).clone());
    result
}

pub fn state_tasks(s: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((s).clone())).clone());
    result
}

pub fn state_path(s: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((second((s).clone())).clone());
    result
}

pub fn update_tasks(s: LlmllVal, new_tasks: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((LlmllVal::from(((new_tasks).clone(), (state_path((s).clone())).clone()))).clone());
    result
}

pub fn req_method(req: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((req).clone())).clone());
    result
}

pub fn req_path(req: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((first((second((req).clone())).clone())).clone());
    result
}

pub fn req_body(req: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((second((second((req).clone())).clone())).clone());
    result
}

pub fn handle_request(state: LlmllVal, req: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from(({ let method = req_method((req).clone()); let path = req_path((req).clone()); let body = req_body((req).clone());match (method).clone() { LlmllVal::Adt(ref ctor, ref args) if ctor == "GET" && args.len() == 1 => { handle_get((state).clone(), (path).clone()) }, LlmllVal::Adt(ref ctor, ref args) if ctor == "POST" && args.len() == 1 => { handle_post((state).clone(), (path).clone(), (body).clone()) }, LlmllVal::Adt(ref ctor, ref args) if ctor == "PUT" && args.len() == 1 => { handle_put((state).clone(), (path).clone(), (body).clone()) }, LlmllVal::Adt(ref ctor, ref args) if ctor == "DELETE" && args.len() == 1 => { handle_delete((state).clone(), (path).clone()) }, _ => LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(405i64)).clone(), (LlmllVal::from("Method Not Allowed".to_string())).clone()))).clone())), _ => panic!("non-exhaustive match in LLMLL") } }).clone());
    result
}

pub fn handle_get(state: LlmllVal, path: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((if (LlmllVal::Bool((path).clone() == (LlmllVal::from("/todos".to_string())).clone())).clone().as_bool() { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(200i64)).clone(), (stringify_tasks((state_tasks((state).clone())).clone())).clone()))).clone())) } else { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(404i64)).clone(), (LlmllVal::from("Not Found".to_string())).clone()))).clone())) }).clone());
    result
}

pub fn handle_post(state: LlmllVal, path: LlmllVal, body: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((if (LlmllVal::Bool((path).clone() == (LlmllVal::from("/todos".to_string())).clone())).clone().as_bool() { match (parse_task_input((body).clone())).clone() { LlmllVal::Adt(ref ctor, ref args) if ctor == "Success" && args.len() == 1 => { let input = args[0].clone(); { let title = first((input).clone()); let comp_pr = second((input).clone()); let comp = first((comp_pr).clone()); let prio = second((comp_pr).clone()); let new_id = int_to_string((now_ms((LlmllVal::Unit).clone())).clone()); let now = now_iso((LlmllVal::Unit).clone()); let new_task = make_task((new_id).clone(), (title).clone(), (LlmllVal::from(false)).clone(), (prio).clone(), (now).clone(), (LlmllVal::from("".to_string())).clone()); let new_tasks = list_append((state_tasks((state).clone())).clone(), (new_task).clone()); let new_state = update_tasks((state).clone(), (new_tasks).clone());LlmllVal::from(((new_state).clone(), (LlmllVal::from(((LlmllVal::from(201i64)).clone(), (LlmllVal::from("Created".to_string())).clone()))).clone())) } }, LlmllVal::Adt(ref ctor, ref args) if ctor == "Error" && args.len() == 1 => { let err = args[0].clone(); LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(400i64)).clone(), (LlmllVal::from("Bad Request".to_string())).clone()))).clone())) }, _ => panic!("non-exhaustive match in LLMLL") } } else { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(404i64)).clone(), (LlmllVal::from("Not Found".to_string())).clone()))).clone())) }).clone());
    result
}

pub fn generate_id(salt: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((int_to_string((((now_ms((LlmllVal::Unit).clone())).clone() + (salt).clone())).clone())).clone());
    result
}

pub fn handle_put(state: LlmllVal, path: LlmllVal, body: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((if (string_starts_with((path).clone(), (LlmllVal::from("/todos/".to_string())).clone())).clone().as_bool() { { let id = string_slice((path).clone(), (LlmllVal::from(7i64)).clone(), (string_length((path).clone())).clone());match (parse_task_input((body).clone())).clone() { LlmllVal::Adt(ref ctor, ref args) if ctor == "Success" && args.len() == 1 => { let input = args[0].clone(); { let title = first((input).clone()); let comp_pr = second((input).clone()); let comp = first((comp_pr).clone()); let prio = second((comp_pr).clone()); let now = now_iso((LlmllVal::Unit).clone()); let new_tasks = list_map((state_tasks((state).clone())).clone(), (| t: LlmllVal | if (LlmllVal::Bool((task_id((t).clone())).clone() == (id).clone())).clone().as_bool() { make_task((id).clone(), (title).clone(), (comp).clone(), (prio).clone(), (task_created((t).clone())).clone(), (now).clone()) } else { t }).clone());if (LlmllVal::Bool((new_tasks).clone() == (state_tasks((state).clone())).clone())).clone().as_bool() { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(404i64)).clone(), (LlmllVal::from("Not Found".to_string())).clone()))).clone())) } else { LlmllVal::from(((update_tasks((state).clone(), (new_tasks).clone())).clone(), (LlmllVal::from(((LlmllVal::from(200i64)).clone(), (LlmllVal::from("OK".to_string())).clone()))).clone())) } } }, LlmllVal::Adt(ref ctor, ref args) if ctor == "Error" && args.len() == 1 => { let err = args[0].clone(); LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(400i64)).clone(), (LlmllVal::from("Bad Request".to_string())).clone()))).clone())) }, _ => panic!("non-exhaustive match in LLMLL") } } } else { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(404i64)).clone(), (LlmllVal::from("Not Found".to_string())).clone()))).clone())) }).clone());
    result
}

pub fn handle_delete(state: LlmllVal, path: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from((if (string_starts_with((path).clone(), (LlmllVal::from("/todos/".to_string())).clone())).clone().as_bool() { { let id = string_slice((path).clone(), (LlmllVal::from(7i64)).clone(), (string_length((path).clone())).clone()); let new_tasks = list_fold((state_tasks((state).clone())).clone(), (list_empty()).clone(), (| acc: LlmllVal, t: LlmllVal | if (LlmllVal::Bool((task_id((t).clone())).clone() != (id).clone())).clone().as_bool() { list_append((acc).clone(), (t).clone()) } else { acc }).clone());LlmllVal::from(((update_tasks((state).clone(), (new_tasks).clone())).clone(), (LlmllVal::from(((LlmllVal::from(204i64)).clone(), (LlmllVal::from("No Content".to_string())).clone()))).clone())) } } else { LlmllVal::from(((state).clone(), (LlmllVal::from(((LlmllVal::from(404i64)).clone(), (LlmllVal::from("Not Found".to_string())).clone()))).clone())) }).clone());
    result
}

pub fn string_starts_with(s: LlmllVal, prefix: LlmllVal) -> LlmllVal {

    let result = LlmllVal::from(({ let len = string_length((prefix).clone());if (LlmllVal::Bool((string_length((s).clone())).clone() >= (len).clone())).clone().as_bool() { LlmllVal::Bool((string_slice((s).clone(), (LlmllVal::from(0i64)).clone(), (len).clone())).clone() == (prefix).clone()) } else { LlmllVal::from(false) } }).clone());
    result
}

